### ISSUE TITLE
Kubevela Terraform application deletion is now failing to delete the underlying resources

### ISSUE THREAD

**Issue by suramasamy** [kubevela/terraform-controller#376]
Kubevela Terraform application deletion is now failing to delete the underlying resources, seems that the terraform destroy execution is getting skipped.
We see the following in the logs,
`I0822 06:58:26.487899       1 configuration_controller.go:175] "performing Configuration Destroy" Namespace="test" Name="bin-repo-app" JobName="95eda79d-7f06-4b9a-8a90-4634ef574905-destroy"
I0822 06:58:26.487911       1 status.go:16] "checking Terraform init and execution status" Namespace="vela-system" Job="95eda79d-7f06-4b9a-8a90-4634ef574905-destroy"
I0822 06:58:26.497866       1 configuration_controller.go:195] No need to execute terraform destroy command, because tfstate file not found: test/bin-repo-app`

It looks like the issue is because of this commit - https://github.com/kubevela/terraform-controller/commit/d2e6f21b29e3c0b94cf1931f2cc93e7aa29ac9ff
The actual secret where the state is stored is present in the vela-system namespace but the code seems to be checking in the namespace where the Kubevela application is created.
Could you please advise?

**Comment by chivalryq** [comment]
Can you please show the application/configuration you are using?

**Comment by suramasamy** [comment]
Please refer below for the test component definition and application yaml files,

`apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  labels:
    type: terraform
  name: example-v1.0.0
  namespace: vela-system
spec:
  schematic:
    terraform:
      configuration: |2-

        variable "ssm_parameter_name" {
          description = "Name of the SSM parameter"
          type        = string
        }

        resource "random_password" "generated_password" {
          length           = 16
          special          = true
          override_special = "_%@"
        }

        resource "aws_ssm_parameter" "password_parameter" {
          name      = var.ssm_parameter_name
          type      = "SecureString"
          value     = random_password.generated_password.result
          overwrite = true
        }

      providerRef:
        name: aws
  workload:
    definition:
      apiVersion: terraform.core.oam.dev/v1beta2
      kind: Configuration
status: {}
`

`apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  labels:
    app: myapp
  name: myapp
  namespace: test
spec:
  components:
  - name: my-app
    properties:
      ssm_parameter_name: abc
    type: example-v1.0.0`

**Comment by jaswalkiranavtar** [comment]
Hi @chivalryq I am on same team as @suramasamy. It looks like the **tfState.Outputs** is empty in our _tfstate-default-<uid>_ secret because of which [this](https://github.com/kubevela/terraform-controller/blob/master/controllers/configuration_controller.go#L1157) condition is evaluating to false and terraform destroy is skipped. Also want to mention that our tfState has resources, it looks like following:

{
  "version": 4,
  "terraform_version": "1.1.9",
  "serial": 4,
  "lineage": "90bc822c-6da1-e2f8-db84-f6d9d3f33a0a",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "alicloud_oss_bucket",
      "name": "bucket-acl",
      "provider": "provider[\"registry.terraform.io/hashicorp/alicloud\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "acl": "private",
            "bucket": "restore-example",
            "cors_rule": [],
            "creation_date": "2022-05-25",
            "extranet_endpoint": "oss-cn-beijing.aliyuncs.com",
            "force_destroy": false,
            "id": "restore-example",
            "intranet_endpoint": "oss-cn-beijing-internal.aliyuncs.com",
            "lifecycle_rule": [],
            "location": "oss-cn-beijing",
            "logging": [],
            "logging_isenable": null,
            "owner": "1170540042370241",
            "policy": "",
            "redundancy_type": "LRS",
            "referer_config": [],
            "server_side_encryption_rule": [],
            "storage_class": "Standard",
            "tags": {},
            "transfer_acceleration": [],
            "versioning": [],
            "website": []
          },
          "sensitive_attributes": [],
          "private": "bnVsbA=="
        }
      ]
    }
  ]
}

Could you please advice how and where (in source-code) _tfstate-default-<uid>_ is created and updated? I was not able to finding it in [configuration_controller.go](https://github.com/kubevela/terraform-controller/blob/master/controllers/configuration_controller.go).

**Comment by chivalryq** [comment]
@jaswalkiranavtar Hi, this state file is not generated by terraform-controller. It is generated by terraform CLI when we specify kubernetes as backend of a configuration. Check the Job execution process.

**Comment by jaswalkiranavtar** [comment]
Thanks for the info @chivalryq. I understood that statefile will be generated as part of "terraform apply" command inside Job container, my question however is, how is the statefile converted to a secret?

**Comment by jaswalkiranavtar** [comment]
@chivalryq did a quick test by running "terraform apply" in oamdev/docker-terraform:1.1.5 docker image in local. The outputs in terraform.tfstate is empty because we don't have any [outputs](https://developer.hashicorp.com/terraform/language/values/outputs) in our ComponentDefinition, as you can also see in the sample shared by @suramasamy  [above](https://github.com/kubevela/terraform-controller/issues/376#issuecomment-1689363548).

But the [logic](https://github.com/kubevela/terraform-controller/blob/master/controllers/configuration_controller.go#L1157) in isTFStateGenerated treats missing outputs as TFState not generated. Isn't that incorrect? It is perfectly normal for a terraform script to not right any outputs. Please let us know if you agree.

**Comment by chivalryq** [comment]
Yes, before we don't have cases that a terraform script don't have any outputs. So we ignore this case. I agree with you.

**Comment by jaswalkiranavtar** [comment]
@chivalryq We completed the testing today by adding an output to ComponentDefinition as a workflow and terraform-destroy is working as expected now.

Created this PR to remove the condition that checks for outputs.

**Comment by chivalryq** [comment]
@jaswalkiranavtar Thanks for contribution! I commented on PR. PTAL
